// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 07/03/2025 11:11:50
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/domin/Coachapp-mobile local/CoachApp-Mobile/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/domin/Coachapp-mobile local/CoachApp-Mobile/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/domin/Coachapp-mobile local/CoachApp-Mobile/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/domin/Coachapp-mobile local/CoachApp-Mobile/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/domin/Coachapp-mobile local/CoachApp-Mobile/plugins/**/*.{js,ts,mjs}","C:/Users/domin/Coachapp-mobile local/CoachApp-Mobile/composables/**/*.{js,ts,mjs}","C:/Users/domin/Coachapp-mobile local/CoachApp-Mobile/utils/**/*.{js,ts,mjs}","C:/Users/domin/Coachapp-mobile local/CoachApp-Mobile/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/domin/Coachapp-mobile local/CoachApp-Mobile/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/domin/Coachapp-mobile local/CoachApp-Mobile/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;